#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://github.com permanent;" /etc/nginx/sites-available/default
service nginx start
