#!/usr/bin/env bash
# Write Bash (init) script 101-manage_my_process that manages manage_my_process
# Requirements:
# When passing the argument start: Starts manage_my_process
# Creates a file containing its PID in /var/run/my_process.pid
# Displays manage_my_process started
# When passing the argument stop: Stops manage_my_process
# Deletes the file /var/run/my_process.pid
# Displays manage_my_process stopped
# When passing the argument restart
# Stops manage_my_process
# Deletes the file /var/run/my_process.pid
# Starts manage_my_process
# Creates a file containing its PID in /var/run/my_process.pid
# Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed.
PIDFILE=/var/run/my_process.pid
PRGM=manage_my_process

if [ "$1" = "start" ];
then
    ./"$PRGM" &
    echo "$!" > "$PIDFILE"
    echo "$PRGM" started
elif [ "$1" = "stop" ];
then
    pkill -SIGKILL -f ./"$PRGM"
    rm "$PIDFILE"
    echo "$PRGM" stopped
elif [ "$1" = "restart" ];
then
    pkill -SIGKILL -f ./"$PRGM"
    rm "$PIDFILE"
    ./"$PRGM" &
    echo "$!" > "$PIDFILE"
    echo "$PRGM" restarted
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
