#!/usr/bin/env bash
# write a Bash script that groups visitors by IP and HTTP status code, and displays this data.
# Requirements: You must use awk, You are not allowed to use while, for, until and cut
awk ' { print $1, $9 } ' apache-access.log | sort -n | uniq -c | sort -nr
