#!/usr/bin/env bash
# Displays  numbers from 1 to 20 using while loop and
# displays "4" and then "bad luck from China" for the 4th loop iteration
# displays "9" and then "bad luck from Japan" for the 9th loop iteration
# displays "17" and then "bad luck from Italy" for the 17th loop iteration
# "for and until loops" are forbidden
# use the "case statement."
number=1
while [ $number -le 20 ]
do
    case $number in
        4)
	    echo -e "$number\nbad luck from China"
	    ;;
	9)
	    echo -e "$number\nbad luck from Japan"
	    ;;
	17)
	    echo -e "$number\nbad luck from Italy"
	    ;;
	*)
	    echo "$number"
	    ;;
    esac
    ((number++))
done
